version: "3.7"
services:
  frontend-angular-fb:
    image: fabiocordobadev/personal:kmila-app
    container_name: frontend-angular-kmila
    restart: always
    ports:
      - 8092:80

  backend-django-fb:
    image: fabiocordobadev/personal:backend-django-fb
    container_name: backend-django-fb
    restart: always
    ports:
      - 8091:8000
    networks:
      - fb-network
    
networks:
  fb-network:
